# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - pam

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Show current path and directory
        run: |
          pwd
          ls -la
          env

      - name: Navigate to root
        run: |
          cd ./yield-optimizer-dashboard
          ls -la

      - name: npm install, build, and test
        run: |
          cd ./yield-optimizer-dashboard
          echo $VITE_BOT_API_URL
          echo "VITE_BOT_API_URL=$VITE_BOT_API_URL\nVITE_PROJECT_ID=$VITE_PROJECT_ID" > .env
          npm install
          npm run build --if-present
          npm run test --if-present
        env: 
          VITE_PROJECT_ID: ${{secrets.VITE_PROJECT_ID}}
          VITE_BOT_API_URL: ${{secrets.VITE_BOT_API_URL}}

      - name: Zip artifact for deployment
        run: |
          cd ./yield-optimizer-dashboard/dist
          zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./yield-optimizer-dashboard/dist/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pam'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AB96828D9772491D99AC0ECEC8FF2614 }}
